"""
Django settings for cafeteria_be project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import secrets
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar las variables de entorno (útil para desarrollo local con .env)
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# 🌟 MODIFICACIÓN CRÍTICA 1: CARGAR SECRET_KEY DESDE VARIABLE DE ENTORNO 🌟
# En Render, debes configurar una variable de entorno llamada SECRET_KEY con un valor seguro.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-=u#gcv7_9^9ny0h_a489n#3h06wb@%h=c8_5%88+hi)mwn(a3q' # Se mantiene solo como fallback (no seguro)
)

# 🌟 MODIFICACIÓN CRÍTICA 2: DESACTIVAR DEBUG EN PRODUCCIÓN 🌟
# Render inyectará esta variable, por defecto estará en False si no existe.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# 🌟 MODIFICACIÓN CRÍTICA 3: HOSTS PERMITIDOS MÁS ROBUSTOS PARA RENDER 🌟
# Permite tu dominio y cualquier dominio *.onrender.com (incluyendo dominios personalizados)
ALLOWED_HOSTS = [
    'cafeteria-be.onrender.com',
    '.onrender.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'djongo',
    'productos',
    'pedidos',
    'usuarios',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# 🌟 MODIFICACIÓN CRÍTICA 4: AÑADIR WHITE NOISE PARA ARCHIVOS ESTÁTICOS 🌟
# WhiteNoise maneja el servicio de archivos estáticos de forma eficiente en producción.
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise debe ir aquí, justo después de SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cafeteria_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cafeteria_be.wsgi.application'

# SIMPLE JWT TOKEN
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "SIGNING_KEY": os.environ.get('JWT_SECRET', secrets.token_urlsafe(32))
}

# CORS
# Las URLs son correctas, asumiendo que cafeteria-fe.onrender.com es tu frontend.
CORS_ALLOWED_ORIGINS = [
    'https://cafeteria-be.onrender.com',
    'https://cafeteria-fe.onrender.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://cafeteria-be.onrender.com',
    'https://cafeteria-fe.onrender.com',
]

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'cafeteriaFeDB',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': os.environ.get(
                'DB_HOST',
                'mongodb+srv://mabejoy_db_user:rLcHj90hRwUHg7rT@cluster0.stv1jqo.mongodb.net/cafeteriaFeDB?retryWrites=true&w=majority'
            ),
            'ssl': True,
            'ssl_cert_reqs': 'CERT_NONE'  # ⚠️ Temporal para evitar handshake error
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# 🌟 MODIFICACIÓN CRÍTICA 6: DEFINIR STATIC_ROOT PARA PRODUCCIÓN 🌟
# Directorio donde Django recolectará todos los archivos estáticos al hacer 'collectstatic'.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'